version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - MONGO_URI=mongodb://db:27017/blogapi
      - REDIS_URL=redis://redis:6379
    networks:
      - backend
    volumes:
      - "./:/app"

  db:
    image: mongo:latest
    volumes:
      - data:/data/db
    networks:
      - backend
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    networks:
      - backend
    ports:
      - "6379:6379"

volumes:
  data:

networks:
  backend:
